name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tags:
    name: Create tags
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@master
      - name: Tag Foo
        uses: tpluscode/action-autotag@min-version-21
        with:
          root: packages/foo
          tag_prefix: "@foo/test/v"
      - name: Tag Bar
        uses: tpluscode/action-autotag@min-version-21
        with:
          root: packages/bar
          tag_prefix: "@foo/bar/v"
      - name: Tag Baz
        uses: tpluscode/action-autotag@min-version-21
        with:
          root: packages/baz
          tag_prefix: "@foo/baz/v"
